# This just runs Python with the Version parameter to test if the running is working

name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Check out repository

      run: |
       python --version
       
    - name: Set destination directory
      run: |
        git config --global myapp.destination /home/ben/booth # Set your destination path here

    - name: Make destination folder
      run: |
        DEST_DIR=$(git config --global myapp.destination)
        mkdir -p "$DEST_DIR"

    - name: Copy from safe directory to destination folder
      run: |
        SAFE_DIR=$(git config --global safe.directory)
        cp -r "$SAFE_DIR/*.py" "$DEST_DIR/"


        
        
